steps:
  # 1. Adım: Bağımlılıkları kur
  - name: 'python:3.9-slim'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - '-i'
      - 'gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.2'
      - '-e'
      - 'DB_USER=${_DB_USER}' 
      - 'DB_PASS=${_DB_PASS}'
      - 'DB_NAME=${_DB_NAME}'
      - 'CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION_NAME}'
      - '--'
      - 'tactile-vial-468307-d3:europe-west3:liveraid-postgres'
      - '--'
      - 'alembic'
      - 'upgrade'
      - 'head'

  # 3. Adım: Uygulamayı Cloud Run'a dağıt
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'liveraid-service' 
      - '--source'
      - '.'
      - '--region'
      - 'europe-west3' 
      - '--add-cloudsql-instances'
      - 'tactile-vial-468307-d3:europe-west3:liveraid-postgres'
      - '--set-env-vars'
      - 'DB_USER=${_DB_USER},DB_PASS=${_DB_PASS},DB_NAME=${_DB_NAME},CLOUD_SQL_CONNECTION_NAME=PROJE_ID:BOLGE:INSTANCE_ADI'
